Fixed /lib paths for archlinux
hartwork/sandwine pull request #34
Opened 2023-09-25 21:37 UTC by zceemja

Great project!

Not working on archlinux, throws obscure error:
```
/usr/bin/winecfg: line 46: /usr/bin/wine: No such file or directory
```
Found similar issue [https://bbs.archlinux.org/viewtopic.php?id=270540](https://bbs.archlinux.org/viewtopic.php?id=270540)

I imagine it should work for every distro as fix should follow unix file structure, but not tested.

2023-09-25 22:02 UTC, hartwork requested changes
Hi @zceemja,

this seems like a combined bug report and fix attempt. The bug report aspect has value but the fix attempt needs more work — e.g. `/lib` as a symlink is unlikely to work on my Gentoo box — so I suggest to take a small step backwards: please create an issue first with `findmnt` output from your Arch box and then we experiment with approaches that have a chance to work for your Arch box and my Gentoo box and the Debian CI at the same time. What do you think?

2023-09-25 22:14 UTC, zceemja commented
Sounds reasonable, will do it later. Maybe also would be smart to find how other projects manage global libs across different distros

2024-08-11 14:27 UTC, task-completer approved these changes
With these changes, sandwine works for me, even if not ideally

2024-08-17 17:38 UTC, hartwork commented
@zceemja @task-completer is there chance that you could try out pull request #61 that I just created for a cross-distro alternative? I'll close this one here as it would break my own setup… Thanks! :pray:

2024-08-17 17:38 UTC, closed without merging