Bind `/dev/input` to have a controller in Wine
hartwork/sandwine pull request #53
Opened 2024-04-24 02:19 UTC by rhjdvsgsgks

https://github.com/libsdl-org/SDL/commit/13e7d1a9583df4323ac78b3afebdc97f48baf42a
https://github.com/libsdl-org/SDL/commit/b0eba1c55df9b4c94ea4762859a47030058fd2df

2024-04-24 17:11 UTC, hartwork requested changes
@rhjdvsgsgks please adjust two details (see below) and also add to the readme in the table of things being shared:

```
| `/dev/input` | read-write bind mount with device access; needs `--raw-input` |
```

2024-04-24 17:11 UTC, hartwork commented on sandwine/_main.py
> +                       help='enable access to /dev/input , to have controller in wine (CAREFUL!) (default: raw-input disabled)')
How about?:

```diff
--- help='enable access to /dev/input , to have controller in wine (CAREFUL!) (default: raw-input disabled)')
+++ help='enable access to /dev/input for a working game controller in Wine (CAREFUL!) (default: /dev/input not forwarded)')
```

2024-04-24 17:11 UTC, hartwork commented on sandwine/_main.py
> +        # default udev based hotplug not working in conatiner
Typo "conatiner"

2025-11-23 19:09 UTC, toboil-features commented
Is it still alive and demanded?

2025-12-03 13:29 UTC, hartwork commented
Closing as superseded by pull request #165…

2025-12-03 13:29 UTC, closed without merging